### ISSUE TITLE
geojson CRS

### ISSUE THREAD

**Issue by galiusha** [JDA-DM/mojxml2geojson#7]
What is the CRS of the resulting geojsons? (after conversion)
I am getting values that exceed the normal (-180, 180) and (-90, 90) scale

**Comment by keichan34** [comment]
When the CRS of the source file is set to "任意座標系" ( `<座標系>任意座標系</座標系>` ), coordinate conversion can't be performed because there is no reference point. In this case, the input coordinates are passed through to the GeoJSON output.

When the CRS of the source file is set to `公共座標XX系` (where XX is a number from 1 to 19), the coordinates are converted to [EPSG:6668](https://epsg.io/6668)
